### ISSUE TITLE
Doesn't work on CLISP

### ISSUE THREAD

**Issue by chaitanyagupta** [Hexstream/first-time-value#1]
If I execute the following forms in the CLISP (2.49 on macOS) REPL:

```
> (defun foo () (first-time-value "xxx"))
> (compile 'foo)
> (foo)
```

I get an error:

```
*** - SYMBOL-VALUE: variable #:GENSYM6474 has no value
```

Backtrace:

```
<1/150> #<SYSTEM-FUNCTION SHOW-STACK> 3
<2/143> #<COMPILED-FUNCTION SYSTEM::PRINT-BACKTRACE>
<3/137> #<COMPILED-FUNCTION SYSTEM::DEBUG-BACKTRACE>
<4/128> #<SYSTEM-FUNCTION SYSTEM::READ-EVAL-PRINT> 2
<5/125> #<COMPILED-FUNCTION SYSTEM::BREAK-LOOP-2-3>
<6/121> #<SYSTEM-FUNCTION SYSTEM::SAME-ENV-AS> 2
<7/107> #<COMPILED-FUNCTION SYSTEM::BREAK-LOOP-2>
<8/105> #<SYSTEM-FUNCTION SYSTEM::DRIVER>
<9/65> #<COMPILED-FUNCTION SYSTEM::BREAK-LOOP>
<10/62> #<SYSTEM-FUNCTION INVOKE-DEBUGGER> 1
<11/52> #<SYSTEM-FUNCTION ERROR>
<12/39> #<COMPILED-FUNCTION SYSTEM::CHECK-VALUE>
<13/37> #<SYSTEM-FUNCTION SYMBOL-VALUE>
<14/35> #<COMPILED-FUNCTION FOO>
```

I don't know if its a CLISP specific issue or something else. If CLISP specific, it might have something to do with this: https://sourceforge.net/p/clisp/bugs/180/

**Comment by Hexstream** [comment]
Thanks for the report, but this looks like a CLISP-specific bug.
The link you posted seems relevant, although I don't want to dig further to confirm.

Since CLISP has not seen a release in 8 years, I recommend using a modern standards-compliant actively supported implementation such as SBCL or CCL.

(See [previous discussion](https://twitter.com/HexstreamSoft/status/1095322179535810561).)
